"""remove email field from user model

Revision ID: 516729489b6c
Revises: b4d2608e7863
Create Date: 2025-05-23 08:28:31.687813

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '516729489b6c'
down_revision = 'b4d2608e7863'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_user_email'), type_='unique')
        batch_op.drop_column('email')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.VARCHAR(length=120), nullable=True))
        batch_op.create_unique_constraint(batch_op.f('uq_user_email'), ['email'])

    # ### end Alembic commands ###
