"""add timetable_type column to timetable

Revision ID: fc21c209ba35
Revises: 516729489b6c
Create Date: 2025-05-25 11:16:32.004739

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc21c209ba35'
down_revision = '516729489b6c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('timetable', schema=None) as batch_op:
        batch_op.add_column(sa.Column('timetable_type', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('timetable', schema=None) as batch_op:
        batch_op.drop_column('timetable_type')

    # ### end Alembic commands ###
